@startuml
class NotificationServiceImpl {
+ void orderPaid(OrderPaidEvent)
+ void orderCancelled(OrderCancelledEvent)
}
interface NotificationService {
~ void orderPaid(OrderPaidEvent)
~ void orderCancelled(OrderCancelledEvent)
}


NotificationService <|.. NotificationServiceImpl
@enduml