server:
  port: 8180

spring:
  application:
    name: warehouse-service
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5Dialect
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/warehouse
    username: root
    password: root
    initialization-mode: always

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /api-docs